### ISSUE TITLE
It's OK to hardcode your deck.

### ISSUE THREAD

**Issue by emgrasmeder** [JetteBke/black-jack#1]
https://github.com/JetteBke/black-jack/blob/1b7d3d0e866a6368bd4a911125eca4753ef6429a/src/black_jack/core.clj#L29

This is a fun algorithm, but I think it's totally fine to make a `standard-52-card-deck.edn` file that basically looks like 
```
{
  :2-of-hearts 2
  :2-of-spades 2
  :2-of-clubs 2
  :2-of-diamonds 2
...
}
```
exactly like that thing you write out in the test file. 
Since there are different types of card decks for different games, but they're constant for the rules of a given game, I think you can make this a data fixture.

Then you can read in the file for the given game, and if you're playing a different game, you'd have a different `.edn` file for that game.

**Comment by JetteBke** [comment]
great idea, I'll do that!
