### ISSUE TITLE
Game doesn't run

### ISSUE THREAD

**Issue by emgrasmeder** [JetteBke/black-jack#3]
I get an error when I try to play the game.

Maybe you could figure out how to add a `travis.yml` or add an end to end /integration test that tries to run as a user
<img width="1438" alt="Screen Shot 2020-09-14 at 1 52 37 PM" src="https://user-images.githubusercontent.com/8107614/93082652-95ac2880-f691-11ea-9feb-f7e53e54f5bc.png">

**Comment by JetteBke** [comment]
ah yes, i changed something and didn't finish so it's currently broken. I am starting all over again anyways :)
